spring:
  application:
    name: ${SPRING_APPLICATION_NAME}

  datasource:
    url: ${SPRING_DATASOURCE}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASS}
    driver-class-name: org.postgresql.Driver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      auto-commit: ${HIBERNATE_CONNECTION_AUTOCOMMIT}

  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO}
    show-sql: ${SPRING_JPA_SHOW_SQL}
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        jdbc:
          fetch_size: ${HIBERNATE_JDBC_FETCH_SIZE}

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
    validate-on-migrate: true

server:
  port: ${SERVER_PORT}

cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS}
  allowed-methods: ${CORS_ALLOWED_METHODS}

jwt:
  secret: ${JWT_SECRET}
  expiration-minutes: ${JWT_EXP_MIN}

logging:
  level:
    root: ${LOG_LEVEL}
    org.hibernate.SQL: ${LOG_SQL}
    com.zaxxer.hikari: WARN
